# Generated by Django 5.1.2 on 2024-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_person_newsletter_abo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_addess',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
