# Generated by Django 5.1.2 on 2024-10-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0008_alter_person_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_addess',
            new_name='email_address',
        ),
    ]
