# Generated by Django 5.1.2 on 2024-10-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0009_rename_email_addess_person_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
